services:
  api:
    build:
      context: ./packages
      dockerfile: Dockerfile
    env_file:
      - ./packages/.env
    environment:
      - HOST=0.0.0.0
      - DB_HOST=mongo
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
